---
#- name: Create temp dir
  #command: mktemp -d
  #register: tmpdir

#- name: Copy RPMS
  #copy: src="{{ rpms_location }}/" dest="{{ tmpdir.stdout }}/"

- name: Register RPM names
  command: ls {{ rpms_dir }}
  register: rpms

- name: Install RPMs with dnf
  dnf: name={{ item }} state=installed
  with_items: "{{ rpms.stdout_lines }}"
  when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 22

- name: Install RPMs with dnf
  yum: name={{ item }} state=installed
  with_items: "{{ rpms.stdout_lines }}"
  when: ansible_os_family == "RedHat" and not (ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 22)

- name: Install RPMs
  dnf: name={{ item }} state=installed
  with_items: "{{ rpms.stdout_lines }}"

#- name: Delete rpms
  #file: path="{{ tmpdir.stdout }}/" state=absent
