---
# tasks file for kshlm.gluster-ssl
- name: Create private key
  command: openssl genrsa -out {{ pkey }} 2048 creates={{ pkey }}

- name: Create self-signed certificate
  command: openssl req -new -x509 -key {{ pkey }} -subj "/CN={{ cname }}" -out {{ cert }} creates={{ cert }}

- name: Fetch certificates
  fetch: src={{ cert }} dest=certs/{{ cname }}.pem flat=yes

- name: Create CA file
  assemble: remote_src=False src=certs/ dest={{ cafile }} owner=root mode=0600

- name: Enable SSL for GlusterD
  file: path={{ glusterd_ssl }} state=touch
  notify: Restart GlusterD
